[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.89"
sorted-list = "0.2.0"
unimock = "0.4.5"
nom = "7.1.1"
r3bl_rs_utils = "0.9.3"